[project]
name = "Sample acris project."
version = "0.1"

# sources = ["samples/add.cw"]
# backend = "cpp"
# backend = "llvm"

# interop_backends = ["python"]
# interop_backends = ["lua"]
# interop_backends = ["python", "lua"]

# Configuration should take release, debug, reldebug, etc.
configuration = "debug"

# Optimization level should be a string or a number.
optimization_level = "fast"

[debug]
loglevel = "verbose"
